apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: staticroutes.networking.digitalocean.com
spec:
  group: networking.digitalocean.com
  names:
    kind: StaticRoute
    plural: staticroutes
    shortNames:
    - sr
    singular: staticroute
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 0
      type: date
    - description: Destination host(s)/subnet(s)
      jsonPath: .spec.destinations
      name: Destinations
      priority: 1
      type: string
    - description: Gateway to route through
      jsonPath: .spec.gateway
      name: Gateway
      priority: 1
      type: string
    - description: Interface to route through
      jsonPath: .spec.interface
      name: Ethernet Interface
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              destinations:
                description: Destination host(s)/subnet(s) to route through the gateway
                  (required)
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                  type: string
                type: array
              force:
                default: false
                description: Force the route to be created (or removed), overriding
                  ip address filtering (optional)
                type: boolean
              gateway:
                description: Gateway to route through (required)
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                type: string
              interface:
                default: eth0
                description: Interface to route through (optional)
                type: string
              remove:
                default: false
                description: Remove the route (optional)
                type: boolean
            required:
            - destinations
            - gateway
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
