apiVersion: v1
kind: Namespace
metadata:
  annotations:
    provider: digitalocean
  name: static-routes
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    provider: digitalocean
  name: staticroutes.networking.digitalocean.com
spec:
  group: networking.digitalocean.com
  names:
    kind: StaticRoute
    plural: staticroutes
    shortNames:
    - sr
    singular: staticroute
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      priority: 1
      type: date
    - description: Node affinity by name (optional)
      jsonPath: .spec.nodeName
      name: Node Name
      priority: 1
      type: string
    - description: Destination host(s)/subnet(s)
      jsonPath: .spec.destinations
      name: Destinations
      priority: 1
      type: string
    - description: Gateway to route through
      jsonPath: .spec.gateway
      name: Gateway
      priority: 1
      type: string
    - description: Interface to route through
      jsonPath: .spec.interface
      name: Ethernet Interface
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              destinations:
                description: Destination host(s)/subnet(s) to route through the gateway
                  (required)
                items:
                  pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$|^([0-9]{1,3}\.){3}[0-9]{1,3}(\/([0-9]|[1-2][0-9]|3[0-2]))?$
                  type: string
                type: array
              force:
                default: false
                description: Force the route to be created (or removed), overriding
                  ip address filtering (optional)
                type: boolean
              gateway:
                description: Gateway to route through (required)
                pattern: ^([0-9]{1,3}\.){3}[0-9]{1,3}$
                type: string
              interface:
                description: Interface to route through (optional)
                type: string
              nodeName:
                description: Node affinity by name (optional)
                type: string
              remove:
                default: false
                description: Remove the route (optional)
                type: boolean
              replace:
                default: false
                description: Replace the route if exists, otherwise add (optional)
                type: boolean
            required:
            - destinations
            - gateway
            type: object
          status:
            type: object
            x-kubernetes-preserve-unknown-fields: true
        type: object
    served: true
    storage: true
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
  namespace: static-routes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
rules:
- apiGroups:
  - networking.digitalocean.com
  resources:
  - clusterkopfpeerings
  verbs:
  - list
  - watch
  - patch
  - get
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
- apiGroups:
  - networking.digitalocean.com
  resources:
  - staticroutes
  verbs:
  - list
  - watch
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: k8s-staticroute-operator
subjects:
- kind: ServiceAccount
  name: k8s-staticroute-operator
  namespace: static-routes
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    provider: digitalocean
  name: k8s-staticroute-operator
  namespace: static-routes
spec:
  selector:
    matchLabels:
      name: k8s-staticroute-operator
  template:
    metadata:
      annotations:
        provider: digitalocean
      labels:
        name: k8s-staticroute-operator
    spec:
      containers:
      - env:
        - name: OPERATOR_NAME
          value: k8s-staticroute-operator
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        image: digitalocean/k8s-staticroute-operator:v1.0.1
        imagePullPolicy: Always
        name: k8s-staticroute-operator
        resources:
          limits:
            memory: 150Mi
          requests:
            memory: 100Mi
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
          readOnlyRootFilesystem: true
          runAsNonRoot: true
      hostNetwork: true
      serviceAccountName: k8s-staticroute-operator
      tolerations:
      - operator: Exists
